apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-bff
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-bff
  template:
    metadata:
      labels:
        app: graphql-bff
    spec:
      containers:
        - name: graphql-bff
          image: graphql-bff:0.2.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: CATALOG_URL
              value: "http://catalog-service.apps.svc.cluster.local:8081/"
            - name: PLAYBACK_URL
              value: "http://playback-service.streaming.svc.cluster.local:8090/"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
